apiVersion: batch/v1
kind: Job
metadata:
  name: tali-exp-1-0d
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - command:
        - /opt/conda/envs/main/bin/accelerate-launch
        - --mixed_precision=bf16
        - /app/tali_wit/run.py
        - exp_name=tali-2-tali_image_text_base_patch16_224-wit_image_text_dataset-42
        - dataset=wit_image_text_dataset
        - model=tali_image_text_base_patch16_224
        - num_workers=12
        - learner.train_iters=100000
        - seed=42
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: tali-exp-1
        - name: NEPTUNE_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: NEPTUNE_API_TOKEN
              name: tali-exp-1
        - name: NEPTUNE_PROJECT
          value: MachineLearningBrewery/tali-exp-1
        - name: NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE
          value: 'TRUE'
        - name: EXPERIMENT_NAME
          value: tali-exp-1
        - name: HF_USERNAME
          value: Antreas
        - name: TOKENIZERS_PARALLELISM
          value: 'False'
        - name: CODE_DIR
          value: /app/
        - name: PROJECT_DIR
          value: /app/
        - name: EXPERIMENT_NAME_PREFIX
          value: tali-exp-1
        - name: EXPERIMENTS_DIR
          value: /experiments/
        - name: EXPERIMENT_DIR
          value: /experiments/
        - name: TALI_DATASET_DIR
          value: /tali-data/
        - name: WIT_DATASET_DIR
          value: /wit-data/
        - name: MODEL_DIR
          value: /model/
        - name: DOCKER_IMAGE_PATH
          value: gcr.io/tali-multi-modal/tali:latest
        image: gcr.io/tali-multi-modal/tali:latest
        imagePullPolicy: Always
        name: job-container
        resources:
          limits:
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /tali-data/
          name: pvc-tali-vol
          readOnly: true
        - mountPath: /wit-data/
          name: pvc-wit0-vol
          readOnly: false
      restartPolicy: Never
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 167Gi
        name: dshm
      - name: pvc-tali-vol
        persistentVolumeClaim:
          claimName: pvc-tali
          readOnly: true
      - name: pvc-wit0-vol
        persistentVolumeClaim:
          claimName: pvc-wit0
          readOnly: false
