#!/bin/bash
export NEPTUNE_API_TOKEN="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJkOTFjMTY5Zi03ZGUwLTQ4ODYtYWI0Zi1kZDEzNjlkMGI5ZjQifQ=="
export NEPTUNE_PROJECT=MachineLearningBrewery/gate-dev-0-8-0
export NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE='TRUE'

export WANDB_API_KEY="821661c6ee1657a2717093701ab76574ae1a9be0"
export WANDB_ENTITY=machinelearningbrewery
export WANDB_PROJECT=tali-godzilla

export KAGGLE_USERNAME="antreasantoniou"
export KAGGLE_KEY="d14aab63e71334cfa118bd5251bf85da"

export PROJECT_DIR=/data1/
export PYTEST_DIR=$PROJECT_DIR

export EXPERIMENT_NAME=tali-godzilla
export HF_USERNAME="Antreas"
export HF_TOKEN=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
export HF_CACHE_DIR=$PYTEST_DIR

export TOKENIZERS_PARALLELISM=False

export CODE_DIR=/devcode/TALI

export EXPERIMENTS_DIR=$PROJECT_DIR
export EXPERIMENT_DIR=$PROJECT_DIR
export TALI_DATASET_DIR=$PROJECT_DIR
export WIT_DATASET_DIR=$PROJECT_DIR/wit/
export MODEL_DIR=$PROJECT_DIR
